Repository datafaker-net/datafaker, pull requests merged in 2024-10, with the labels that each got.

#1369 #1368 fix "Duplicate key error" when a custom faker has multiple methods with the same return type.
  src/main/java/net/datafaker/providers/base/ObjectMethods.java
  src/test/java/net/datafaker/providers/base/ObjectMethodsTest.java
Labels: bug

#1383 describe principles of languages/countries to CONTRIBUTING guide
  CONTRIBUTING.md
Labels: documentation

#1381 #1306 fix non-thread-safe usages of CopyOnWriteMap
  src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
  src/main/java/net/datafaker/service/FakeValuesService.java
Labels: bug

#1396 #1394 add Estonian and Latvian universities
  src/main/resources/en/university.yml
Labels: enhancement

#1397 add missing @Override annotations
  src/main/java/net/datafaker/providers/base/BaseFaker.java
  src/main/java/net/datafaker/sequence/FakeCollection.java
  src/main/java/net/datafaker/sequence/FakeStream.java
  src/main/java/net/datafaker/transformations/JsonTransformer.java
  src/test/java/net/datafaker/AbstractFakerTest.java
  src/test/java/net/datafaker/providers/foods/HebrewFoodTest.java
Labels: enhancement

#1410 Add greek translations for Measurement provider & other Greek tests
  src/main/resources/el-GR.yml
  src/test/java/net/datafaker/providers/base/AncientTest.java
  src/test/java/net/datafaker/providers/base/BaseFakerTest.java
  src/test/java/net/datafaker/providers/base/GreekPhilosopherTest.java
  src/test/java/net/datafaker/providers/base/JobTest.java
  src/test/java/net/datafaker/providers/base/MeasurementTest.java
Labels: hacktoberfest-accepted

#1415 Feature/name el gr
  src/main/resources/el-GR.yml
  src/test/java/net/datafaker/providers/base/NameTest.java
Labels: hacktoberfest-accepted

#1417 fix flaky test `NameTest.java` with Greek names
  src/main/resources/el-GR.yml
Labels: bug

#1416 Feature: new methods `nextInt(Range)` and `nextLong(Range)`
  src/main/java/net/datafaker/providers/base/Barcode.java
  src/main/java/net/datafaker/providers/base/DateAndTime.java
  src/main/java/net/datafaker/providers/base/Number.java
  src/main/java/net/datafaker/service/RandomService.java
  src/main/java/net/datafaker/service/Range.java
  src/test/java/net/datafaker/providers/base/NumberTest.java
  src/test/java/net/datafaker/providers/base/TimeAndDateTest.java
  src/test/java/net/datafaker/providers/base/UniqueTest.java
  src/test/java/net/datafaker/service/RandomNumbersTest.java
  src/test/java/net/datafaker/service/RandomServiceTest.java
  src/test/java/net/datafaker/service/RangeTest.java
Labels: enhancement

#1420 fix flaky UniversityTest
  src/test/java/net/datafaker/providers/base/UniversityTest.java
Labels: enhancement
