Repository datafaker-net/datafaker, pull requests merged in 2024-12, with the labels that each got.

#1458 swedish ssn symbol depends on birthday date of person
  src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
  src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
Labels: bug

#1460 simplify few tests
  src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
  src/test/java/net/datafaker/helpers/IdNumberPatterns.java
  src/test/java/net/datafaker/idnumbers/PolishIdNumberTest.java
  src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
Labels: refactoring

#1462 Documentation: Add missing build() part to example
  docs/documentation/password.md
Labels: bug, documentation

#1465 Respect arg types while looking for method for expressions
  src/main/java/net/datafaker/service/FakeValuesService.java
  src/test/java/net/datafaker/FakerTest.java
Labels: enhancement

#1467 Use jdk 23 in ci
  .github/workflows/build.yml
Labels: enhancement
