Repository datafaker-net/datafaker, pull requests merged in 2025-08, with the labels that each got.

#1601 [build] Use jdk25-ea in CI
  .github/workflows/build.yml
Labels: enhancement, github_actions, java

#1620 #1617 avoid useless `NoSuchMethodRuntimeException` in logs
  src/main/java/net/datafaker/service/FakeValuesService.java
Labels: bug

#1628 Creates new Credential provider; Deprecated Internet provider methods
  src/main/java/net/datafaker/providers/base/BaseProviders.java
  src/main/java/net/datafaker/providers/base/Credential.java
  src/main/java/net/datafaker/providers/base/Internet.java
  src/main/java/net/datafaker/service/files/EnFile.java
  src/main/resources/en/credential.yml
  src/test/java/net/datafaker/providers/base/CredentialTest.java
  src/test/java/net/datafaker/providers/base/InternetTest.java
Labels: enhancement

#1631 make Brazilian ID Number accessible via `faker.idNumber()`
  src/main/java/net/datafaker/idnumbers/BrazilIdNumber.java
  src/main/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtil.java
  src/main/java/net/datafaker/providers/base/IdNumber.java
  src/main/resources/META-INF/services/net.datafaker.idnumbers.IdNumberGenerator
  src/test/java/net/datafaker/helpers/IdNumberPatterns.java
  src/test/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtilTest.java
  src/test/java/net/datafaker/providers/base/CPFTest.java
  src/test/java/net/datafaker/providers/base/IdNumberTest.java
Labels: enhancement
