Repository datafaker-net/datafaker, pull requests merged in 2025-09, with the labels that each got.

#1635 Fix Correct typo in kpop.boy_bands key in ko.yml
  src/main/resources/ko.yml
Labels: bug

#1636 Feat Improve Korean name data in ko.yml
  src/main/resources/ko.yml
Labels: enhancement

#1646 Less logs in tests
  pom.xml
  src/main/java/net/datafaker/providers/base/BaseProviders.java
  src/main/java/net/datafaker/providers/base/IdNumber.java
  src/main/java/net/datafaker/providers/base/Lorem.java
  src/main/java/net/datafaker/providers/base/Name.java
  src/main/java/net/datafaker/providers/base/TimeAndDate.java
  src/test/java/net/datafaker/TestSetupExtension.java
  src/test/java/net/datafaker/formats/CsvTest.java
  src/test/java/net/datafaker/formats/JsonTest.java
  src/test/java/net/datafaker/formats/SqlTest.java
  src/test/java/net/datafaker/idnumbers/MexicanIdNumberTest.java
  src/test/java/net/datafaker/providers/base/CurrencyTest.java
  src/test/java/net/datafaker/providers/base/CustomFakerTest.java
  src/test/java/net/datafaker/providers/base/FinanceTest.java
  src/test/java/net/datafaker/providers/base/IdNumberTest.java
  src/test/java/net/datafaker/providers/base/InternetPasswordTest.java
  src/test/java/net/datafaker/providers/base/InternetTest.java
  src/test/java/net/datafaker/providers/base/MedicalTest.java
  src/test/java/net/datafaker/providers/base/TwitterTest.java
Labels: refactoring

#1662 Added missing link for deprecation warning.
  src/main/java/net/datafaker/providers/base/Internet.java
Labels: documentation
